Web into master

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,34 +5,28 @@ stages:
   - test
   - publish
 
-dartdoc_programmable_video:
-  stage: lint
-  script:
-    - cd programmable_video
-    - flutter pub get
-    - flutter pub global activate dartdoc 4.1.0
-    - flutter pub global run dartdoc 4.1.0 --no-auto-include-dependencies --quiet # until the issue is resolved https://github.com/dart-lang/dartdoc/issues/2934
-  only:
-    refs:
-      - merge_requests
-    changes:
-      - programmable_video/lib/**/*
-      - programmable_video/README.md
-      - .gitlab-ci.yml
+.projects: &projects
+  parallel:
+    matrix:
+      - PROJECT: programmable_video
+      - PROJECT: programmable_video_platform_interface
+      - PROJECT: programmable_video_web
 
-dartdoc_platform_interface:
+dartdoc:
+  <<: *projects
   stage: lint
   script:
-    - cd programmable_video_platform_interface
+    - cd "${PROJECT}"
     - flutter pub get
     - flutter pub global activate dartdoc 4.1.0
     - flutter pub global run dartdoc 4.1.0 --no-auto-include-dependencies --quiet # until the issue is resolved https://github.com/dart-lang/dartdoc/issues/2934 
   only:
     refs:
       - merge_requests
+      - master
     changes:
-      - programmable_video_platform_interface/lib/**/*
-      - programmable_video_platform_interface/README.md
+      - ./**/*.dart
+      - ./**/README.md
       - .gitlab-ci.yml
 
 firebase_functions_programmable_video:
@@ -50,35 +44,21 @@ firebase_functions_programmable_video:
       - programmable_video/example/firebase/functions/**/*
       - .gitlab-ci.yml
 
-flutter_analyze_programmable_video:
+flutter_analyze:
+  <<: *projects
   stage: lint
   script:
-    - cd programmable_video/example || exit 1
+    - cd "${PROJECT}"
     - flutter pub get
-    - cd .. || exit 1
     - flutter analyze --pub
     - flutter format -l 240 -n . --set-exit-if-changed
   only:
     refs:
       - merge_requests
+      - master
     changes:
-      - programmable_video/lib/**/*.dart
-      - programmable_video/test/**/*.dart
-      - programmable_video/example/lib/**/*.dart
-      - programmable_video/example/test/**/*.dart
-      - .gitlab-ci.yml
-
-flutter_analyze_platform_interface:
-  stage: lint
-  script:
-    - cd programmable_video_platform_interface
-    - flutter analyze --pub
-    - flutter format -l 240 -n . --set-exit-if-changed
-  only:
-    refs:
-      - merge_requests
-    changes:
-      - programmable_video_platform_interface/lib/**/*.dart
+      - ./**/*.dart
+      - ./**/test/**/*.dart
       - .gitlab-ci.yml
 
 kotlin_analyze_programmable_video:
@@ -147,35 +127,50 @@ unit_test:
       - programmable_video_platform_interface/test/**/*
       - .gitlab-ci.yml
 
-dry-run_programmable_video:
-  stage: publish
-  script:
-    - cd programmable_video
-    - flutter pub get
-    - sudo add-apt-repository ppa:rmescandon/yq -y
-    - sudo apt update
-    - sudo apt install yq -y
-    - platformInterfaceVersion=$(yq eval '.version' ../programmable_video_platform_interface/pubspec.yaml | sed 's/\+.*$//')
-    - yq eval -i ".dependencies.twilio_programmable_video_platform_interface=\"^${platformInterfaceVersion}\"" pubspec.yaml
-    - flutter pub publish --dry-run
-  only:
-    refs:
-      - merge_requests
-    changes:
-      - programmable_video/**/*
-      - .gitlab-ci.yml
-
-dry-run_platform_interface:
+pub_publish-dry_run-platform_interface:
   stage: publish
   script:
     - cd programmable_video_platform_interface
+    - flutter pub publish --dry-run
+  only:
+    refs:
+      - merge_requests
+    changes:
+      - ./programmable_video_platform_interface/**/*
+      - .gitlab-ci.yml
+
+pub_publish-dry_run-programmable_video:
+  stage: publish
+  script:
+    - cd programmable_video
+    - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
+    - platformInterfaceVersion=$(yq eval '.version' ../programmable_video_platform_interface/pubspec.yaml | sed 's/\+.*$//')
+    - yq eval -i ".dependencies.twilio_programmable_video_platform_interface=\"^${platformInterfaceVersion}\"" pubspec.yaml
+    - webVersion=$(yq eval '.version' ../programmable_video_web/pubspec.yaml | sed 's/\+.*$//')
+    - yq eval -i ".dependencies.twilio_programmable_video_web=\"^${webVersion}\"" pubspec.yaml
     - flutter pub get
     - flutter pub publish --dry-run
   only:
     refs:
       - merge_requests
     changes:
-      - programmable_video_platform_interface/**/*
+      - ./programmable_video/**/*
+      - .gitlab-ci.yml
+
+pub_publish-dry_run-programmable_video_web:
+  stage: publish
+  script:
+    - cd programmable_video_web
+    - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
+    - platformInterfaceVersion=$(yq eval '.version' ../programmable_video_platform_interface/pubspec.yaml | sed 's/\+.*$//')
+    - yq eval -i ".dependencies.twilio_programmable_video_platform_interface=\"^${platformInterfaceVersion}\"" pubspec.yaml
+    - flutter pub get
+    - flutter pub publish --dry-run
+  only:
+    refs:
+      - merge_requests
+    changes:
+      - ./programmable_video_web/**/*
       - .gitlab-ci.yml
 
 firebase_programmable_video:
@@ -285,16 +280,63 @@ pub-dev_programmable_video:
       }
       EOF
     - cd programmable_video
-    - sudo add-apt-repository ppa:rmescandon/yq -y
-    - sudo apt update
-    - sudo apt install yq -y
+    - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
+    - platformInterfaceVersion=$(yq eval '.version' ../programmable_video_platform_interface/pubspec.yaml | sed 's/\+.*$//')
+    - yq eval -i ".dependencies.twilio_programmable_video_platform_interface=\"^${platformInterfaceVersion}\"" pubspec.yaml
+    - webVersion=$(yq eval '.version' ../programmable_video_web/pubspec.yaml | sed 's/\+.*$//')
+    - yq eval -i ".dependencies.twilio_programmable_video_web=\"^${webVersion}\"" pubspec.yaml
+    - flutter pub get
+    - flutter pub publish -f
+  only:
+    refs:
+      - /^programmable-video_v.*$/
+  except:
+    refs:
+      - branches
+
+pub-dev_programmable_web:
+  # https://robertohuertas.com/2019/01/20/publish-flutter-package-with-travis/
+  stage: publish
+  script:
+    - |
+      if [ -z "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_ACCESS_TOKEN environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_REFRESH_TOKEN environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_TOKEN_ENDPOINT environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_EXPIRATION}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_EXPIRATION environment variable"
+        exit 1
+      fi
+
+      cat <<EOF > ~/.pub-cache/credentials.json
+      {
+        "accessToken":"$(echo "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" | base64 -d)",
+        "refreshToken":"$(echo "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" | base64 -d)",
+        "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
+        "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
+        "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
+      }
+      EOF
+    - cd programmable_video_web
+    - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
     - platformInterfaceVersion=$(yq eval '.version' ../programmable_video_platform_interface/pubspec.yaml | sed 's/\+.*$//')
     - yq eval -i ".dependencies.twilio_programmable_video_platform_interface=\"^${platformInterfaceVersion}\"" pubspec.yaml
     - flutter pub get
     - flutter pub publish -f
   only:
     refs:
-      - /^programmable-video_v.*$/
+      - /^programmable-video-web_v.*$/
   except:
     refs:
       - branches
@@ -366,8 +408,8 @@ tag_programmable_video:
       export TAG_NAME="$(awk '/^version: /{print $NF}' pubspec.yaml)"
       curl --fail --request POST --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
         --data-urlencode "tag_name=programmable-video_v${TAG_NAME}" \
-        --data-urlencode "ref=master" \
-        --data-urlencode "message=Check the [CHANGELOG.md](${CI_PROJECT_URL}/-/blob/master/programmable_video/CHANGELOG.md)" \
+        --data-urlencode "ref=${CI_COMMIT_REF_NAME}" \
+        --data-urlencode "message=Check the [CHANGELOG.md](${CI_PROJECT_URL}/-/blob/${CI_COMMIT_REF_NAME}/programmable_video/CHANGELOG.md)" \
         "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags"
   environment:
     name: pub-dev-plugin
@@ -376,6 +418,7 @@ tag_programmable_video:
   only:
     refs:
       - master
+      - web
     changes:
       - programmable_video/**/*
       - .gitlab-ci.yml
@@ -395,8 +438,8 @@ tag_platform_interface:
       export TAG_NAME="$(awk '/^version: /{print $NF}' pubspec.yaml)"
       curl --fail --request POST --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
         --data-urlencode "tag_name=programmable-video-platform-interface_v${TAG_NAME}" \
-        --data-urlencode "ref=master" \
-        --data-urlencode "message=Check the [CHANGELOG.md](${CI_PROJECT_URL}/-/blob/master/programmable_video_platform_interface/CHANGELOG.md)" \
+        --data-urlencode "ref=${CI_COMMIT_REF_NAME}" \
+        --data-urlencode "message=Check the [CHANGELOG.md](${CI_PROJECT_URL}/-/blob/${CI_COMMIT_REF_NAME}/programmable_video_platform_interface/CHANGELOG.md)" \
         "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags"
   environment:
     name: pub-dev-platform-interface
@@ -405,6 +448,37 @@ tag_platform_interface:
   only:
     refs:
       - master
+      - web
     changes:
       - programmable_video_platform_interface/**/*
+      - .gitlab-ci.yml
+
+tag_platform_web:
+  image: curlimages/curl
+  stage: publish
+  script:
+    - |
+      cd programmable_video_web || exit 1
+
+      if [ -z "${GITLAB_API_TOKEN}" ]; then
+        echo "Missing GITLAB_API_TOKEN environment variable"
+        exit 1
+      fi
+
+      export TAG_NAME="$(awk '/^version: /{print $NF}' pubspec.yaml)"
+      curl --fail --request POST --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
+        --data-urlencode "tag_name=programmable-video-web_v${TAG_NAME}" \
+        --data-urlencode "ref=${CI_COMMIT_REF_NAME}" \
+        --data-urlencode "message=Check the [CHANGELOG.md](${CI_PROJECT_URL}/-/blob/${CI_COMMIT_REF_NAME}/programmable_video_web/CHANGELOG.md)" \
+        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags"
+  environment:
+    name: pub-dev-web
+    url: https://pub.dev/packages/twilio_programmable_video_web
+  when: manual
+  only:
+    refs:
+      - master
+      - web
+    changes:
+      - programmable_video_web/**/*
       - .gitlab-ci.yml
